#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const indexPath = path.join(rootDir, 'index.js');
const binDir = path.join(rootDir, 'bin');
const cliPath = path.join(binDir, 'cli.js');

console.log('Building CLI from index.js...\n');

try {
  // Read the index.js file
  const indexContent = fs.readFileSync(indexPath, 'utf8');

  // Create the CLI wrapper template
  const cliTemplate = `#!/usr/bin/env node

// This file is auto-generated from index.js by the build script
// Do not edit this file directly - edit index.js instead and run: npm run build

${indexContent}

// CLI execution logic
const targetDir = process.argv[2] || process.cwd();
const absolutePath = path.resolve(targetDir);

console.log(\`Scanning directory: \${absolutePath}\\n\`);

try {
  const directories = scanDirectory(absolutePath);
  
  if (directories.length === 0) {
    console.log('No subdirectories found.');
  } else {
    console.log('Found subdirectories:');
    console.log('-------------------');
    directories.forEach(dir => {
      console.log(\`  - \${dir}\`);
    });
    console.log(\`\\nTotal: \${directories.length} subdirectories\`);
  }
} catch (error) {
  console.error(\`Error: \${error.message}\`);
  process.exit(1);
}
`;

  // Ensure bin directory exists
  if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, { recursive: true });
    console.log('✓ Created bin/ directory');
  }

  // Write the CLI file
  fs.writeFileSync(cliPath, cliTemplate, 'utf8');
  console.log('✓ Generated bin/cli.js from index.js');

  // Make it executable
  fs.chmodSync(cliPath, '755');
  console.log('✓ Made bin/cli.js executable');

  console.log('\n✨ Build completed successfully!\n');
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}

