#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const indexPath = path.join(rootDir, 'index.js');
const binDir = path.join(rootDir, 'bin');
const cliPath = path.join(binDir, 'cli.js');

console.log('Building CLI from index.js...\n');

try {
  // Read the index.js file
  const indexContent = fs.readFileSync(indexPath, 'utf8');

  // Create the CLI wrapper template
  const cliTemplate = `#!/usr/bin/env node

// This file is auto-generated from index.js by the build script
// Do not edit this file directly - edit index.js instead and run: npm run build

${indexContent}

// CLI execution logic
const args = process.argv.slice(2);
const targetDir = args[0] || process.cwd();
const outputFile = args[1] || null; // Optional output file path

console.log('🔍 Scanning for Node.js repositories...\\n');
console.log(\`Target Directory: \${targetDir}\`);

try {
  const result = generateDependenciesReport(targetDir, outputFile);
  
  console.log(\`\\n✅ Found \${result.repositories.length} Node.js repositories\`);
  console.log(\`📄 Report saved to: \${result.outputFile}\\n\`);
  
  // Print summary
  if (result.repositories.length > 0) {
    console.log('Summary:');
    console.log('-'.repeat(60));
    result.repositories.forEach(repo => {
      const totalDeps = repo.dependencies.length + repo.devDependencies.length;
      console.log(\`  \${repo.name}: \${totalDeps} total dependencies (\${repo.dependencies.length} prod, \${repo.devDependencies.length} dev)\`);
    });
    console.log('\\n💡 Check the report file for detailed information.');
  } else {
    console.log('No Node.js repositories found in the specified directory.');
  }
} catch (error) {
  console.error(\`\\n❌ Error: \${error.message}\`);
  process.exit(1);
}
`;

  // Ensure bin directory exists
  if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, { recursive: true });
    console.log('✓ Created bin/ directory');
  }

  // Write the CLI file
  fs.writeFileSync(cliPath, cliTemplate, 'utf8');
  console.log('✓ Generated bin/cli.js from index.js');

  // Make it executable
  fs.chmodSync(cliPath, '755');
  console.log('✓ Made bin/cli.js executable');

  console.log('\n✨ Build completed successfully!\n');
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}

